---
toc: false
---
## An Investigation of Debt Delinquency Across the United States (Dec 2025)

My final group project in Stats 140XP examined how debt delinquency rates vary within socioeconomic and demographic characteristics, with particular attention to childhood family income. Read our final report [here](/140xpfinalreport.pdf): 

# Heavy-Tailed Reward Distributions for Multiplayer Bandits (April 2025)

This paper explores the multi-arm bandit problem and extends the study of heavy-tailed bandits to the multi-agent setting, where multiple players interact in environments
with varying levels of information asymmetry. Read more about our paper [here](/heavy_tail.pdf)

# Coordinating for Clicks: Learning in Multi-Agent Information Asymmetric Cascading Bandits (Feb 2025)

This paper builds on the decentralized, cooperative multi-agent bandit framework and apply it to the previously researchedstochastic partial-monitoring cascading bandit problem. We contend with three variants of information asymmetry: action asymmetry, reward asymmetry, and that with both action and reward asymmetry. Read more about our paper [here](/cascading.pdf)